	$(document).ready(function(){
	$("#pageEnregistrer").hide();	
	$("#pageIdentifier").hide();
	$("#confirmer").hide();
	$("#profilpage").hide();
	$("#titre1").hide();
	$("#titre2").hide();
	$("#titre4").hide();
	$("#eventboard").show();
	$("#creerevent").hide();
	$("#pageprofil").hide();
	$("#pagereglage").hide();	

	$("#profil").click(function(){
		$("#titre1").show();
		$("#titre2").hide();
		$("#titre3").hide();
		$("#titre4").hide();
		$("#eventboard").hide();
		$("#creerevent").hide();
		$("#pageprofil").show();
		$("#pagereglage").hide();			
	});
	$("#programme").click(function(){
		$("#titre1").hide();
		$("#titre2").show();
		$("#titre3").hide();
		$("#titre4").hide();
		$("#eventboard").show();
		$("#creerevent").hide();
		$("#pageprofil").hide();
		$("#pagereglage").hide();		
	});
	$("#eventdispo").click(function(){
		$("#titre1").hide();
		$("#titre2").hide();
		$("#titre3").show();
		$("#titre4").hide();
		$("#eventboard").show();
		$("#creerevent").hide();
		$("#pageprofil").hide();
		$("#pagereglage").hide();		
	});
	$("#settings").click(function(){
		$("#titre1").hide();
		$("#titre2").hide();
		$("#titre3").hide();
		$("#titre4").show();
		$("#eventboard").hide();
		$("#creerevent").hide();
		$("#pageprofil").hide();
		$("#pagereglage").show();	
	});
	$("#creerevent1").click(function(){
		$("#pageprofil").hide();
		$("#pagereglage").hide();
		$("#eventboard").hide();
		$("#creerevent").show();
	});
	$("#creerevent2").click(function(){
		$("#pageprofil").hide();
		$("#pagereglage").hide();
		$("#eventboard").hide();
		$("#creerevent").show();
	});
	$("#uploadlinkd").click(function(){
		

	});
	});
